@ConsultaCreditoService.Api_HostAddress = http://localhost:5025

POST {{ConsultaCreditoService.Api_HostAddress}}/api/creditos/integrar-credito-constituido
Content-Type: application/json
[
  {
    "numeroCredito": "123456",
    "numeroNfse": "7891011",
    "dataConstituicao": "2024-02-25",
    "valorIssqn": 1500.75,
    "tipoCredito": "ISSQN",
    "simplesNacional": "Sim",
    "aliquota": 5.0,
    "valorFaturado": 30000.00,
    "valorDeducao": 5000.00,
    "baseCalculo": 25000.00
  },
  {
    "numeroCredito": "789012",
    "numeroNfse": "7891011",
    "dataConstituicao": "2024-02-26",
    "valorIssqn": 1200.50,
    "tipoCredito": "ISSQN",
    "simplesNacional": "Não",
    "aliquota": 4.5,
    "valorFaturado": 25000.00,
    "valorDeducao": 4000.00,
    "baseCalculo": 21000.00
  },
  {
    "numeroCredito": "654321",
    "numeroNfse": "1122334",
    "dataConstituicao": "2024-01-15",
    "valorIssqn": 800.50,
    "tipoCredito": "Outros",
    "simplesNacional": "Sim",
    "aliquota": 3.5,
    "valorFaturado": 20000.00,
    "valorDeducao": 3000.00,
    "baseCalculo": 17000.00
  }
]
###
